name: REPL build linux64-tcc

on:
  push:
    branches: [ $default-branch, main ]
  pull_request:
    branches: [ $default-branch, main ]

jobs:
  build_tcc:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: tcc
    
    - name: Build REPL
      run: ./gen_code.sh && cd repl && ./fastbuild.sh -shared
